trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'
- bash: echo Agent OS $(Agent.OS)
- bash: echo $(System.DefaultWorkingDirectory)
- bash: ls -R $(System.DefaultWorkingDirectory)

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    architecture: 'x64'
- task: PublishTestResults@2
  inputs:
    testResultsFiles: "**/TEST-*.xml"